//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionSistemaVentura {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AplicacionSistemaVentura.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string EjecControlNeumaticoBTNG_CONS1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoBTNG_CONS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string EjecControlNeumaticoBTNG_EDIT1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoBTNG_EDIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string EjecControlNeumaticoBTNG_NUEV1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoBTNG_NUEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutar Control de Neumatico.
        /// </summary>
        internal static string EjecControlNeumaticoFORM_CAPT1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoFORM_CAPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición satisfactoria.
        /// </summary>
        internal static string EjecControlNeumaticoGRAB_EDIT1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoGRAB_EDIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación Satisfactoria.
        /// </summary>
        internal static string EjecControlNeumaticoGRAB_NUEV1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoGRAB_NUEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Control Neumatico ya existe.
        /// </summary>
        internal static string EjecControlNeumaticoLOGI_DUPL1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoLOGI_DUPL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una Ciclo.
        /// </summary>
        internal static string EjecControlNeumaticoOBLI_CICLO {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoOBLI_CICLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo obsercación no admite valores en blanco.
        /// </summary>
        internal static string EjecControlNeumaticoOBLI_DESC1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoOBLI_DESC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un estado.
        /// </summary>
        internal static string EjecControlNeumaticoOBLI_ESTA1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoOBLI_ESTA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una Unidad de Control.
        /// </summary>
        internal static string EjecControlNeumaticoOBLI_UC {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoOBLI_UC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Control de Neumatico.
        /// </summary>
        internal static string EjecControlNeumaticoTAB0_CAPT1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoTAB0_CAPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Control de Neumático.
        /// </summary>
        internal static string EjecControlNeumaticoTAB1_CONS1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoTAB1_CONS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Control de Neumático.
        /// </summary>
        internal static string EjecControlNeumaticoTAB1_EDIT1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoTAB1_EDIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Control de Neumático.
        /// </summary>
        internal static string EjecControlNeumaticoTAB1_NUEV1 {
            get {
                return ResourceManager.GetString("EjecControlNeumaticoTAB1_NUEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string EjecGestRegInciBTNG_CONS {
            get {
                return ResourceManager.GetString("EjecGestRegInciBTNG_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string EjecGestRegInciBTNG_EDIT {
            get {
                return ResourceManager.GetString("EjecGestRegInciBTNG_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string EjecGestRegInciBTNG_NUEV {
            get {
                return ResourceManager.GetString("EjecGestRegInciBTNG_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ciclo que desea agregar ya existe, agrege otro..
        /// </summary>
        internal static string EjecGestRegInciCICLO_DUPL {
            get {
                return ResourceManager.GetString("EjecGestRegInciCICLO_DUPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión Registro de Incidencia.
        /// </summary>
        internal static string EjecGestRegInciFORM_CAPT {
            get {
                return ResourceManager.GetString("EjecGestRegInciFORM_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición satisfactoria.
        /// </summary>
        internal static string EjecGestRegInciGRAB_EDIT {
            get {
                return ResourceManager.GetString("EjecGestRegInciGRAB_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación Satisfactoria.
        /// </summary>
        internal static string EjecGestRegInciGRAB_NUEV {
            get {
                return ResourceManager.GetString("EjecGestRegInciGRAB_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo contador final no admite valores en blanco.
        /// </summary>
        internal static string EjecGestRegInciOBLI_CF {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo contador final no admite valor 0.
        /// </summary>
        internal static string EjecGestRegInciOBLI_CF0 {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_CF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo contador inicial no admite valores en blanco.
        /// </summary>
        internal static string EjecGestRegInciOBLI_CI {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo contador incial no admite valor 0.
        /// </summary>
        internal static string EjecGestRegInciOBLI_CI0 {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_CI0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un estado de Incidencia.
        /// </summary>
        internal static string EjecGestRegInciOBLI_EST {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_EST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un fecha.
        /// </summary>
        internal static string EjecGestRegInciOBLI_FEC {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_FEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un responsable.
        /// </summary>
        internal static string EjecGestRegInciOBLI_RESP {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_RESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un solicitante.
        /// </summary>
        internal static string EjecGestRegInciOBLI_SOLI {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_SOLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un tipo de Incidencia.
        /// </summary>
        internal static string EjecGestRegInciOBLI_TIN {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_TIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una Unidad de Control.
        /// </summary>
        internal static string EjecGestRegInciOBLI_UC {
            get {
                return ResourceManager.GetString("EjecGestRegInciOBLI_UC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Incidencias.
        /// </summary>
        internal static string EjecGestRegInciTAB0_CAPT {
            get {
                return ResourceManager.GetString("EjecGestRegInciTAB0_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Incidencia.
        /// </summary>
        internal static string EjecGestRegInciTAB1_CONS {
            get {
                return ResourceManager.GetString("EjecGestRegInciTAB1_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Incidencia.
        /// </summary>
        internal static string EjecGestRegInciTAB1_EDIT {
            get {
                return ResourceManager.GetString("EjecGestRegInciTAB1_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Incidencia.
        /// </summary>
        internal static string EjecGestRegInciTAB1_NUEV {
            get {
                return ResourceManager.GetString("EjecGestRegInciTAB1_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ciclo que desea agregar ya existe, elija otro por favor..
        /// </summary>
        internal static string EjecGestRegInciVALI_EXIS {
            get {
                return ResourceManager.GetString("EjecGestRegInciVALI_EXIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo contador inicial no debe ser mayor o igual al campo contador final..
        /// </summary>
        internal static string EjecGestRegInciVALI_MAY {
            get {
                return ResourceManager.GetString("EjecGestRegInciVALI_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo contador final no debe ser menor o igual al campo contador inicial..
        /// </summary>
        internal static string EjecGestRegInciVALI_MEN {
            get {
                return ResourceManager.GetString("EjecGestRegInciVALI_MEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string GestActividadBTNG_CONS {
            get {
                return ResourceManager.GetString("GestActividadBTNG_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string GestActividadBTNG_EDIT {
            get {
                return ResourceManager.GetString("GestActividadBTNG_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string GestActividadBTNG_NUEV {
            get {
                return ResourceManager.GetString("GestActividadBTNG_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión Actividad.
        /// </summary>
        internal static string GestActividadFORM_CAPT {
            get {
                return ResourceManager.GetString("GestActividadFORM_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición satisfactoria.
        /// </summary>
        internal static string GestActividadGRAB_EDIT {
            get {
                return ResourceManager.GetString("GestActividadGRAB_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación Satisfactoria.
        /// </summary>
        internal static string GestActividadGRAB_NUEV {
            get {
                return ResourceManager.GetString("GestActividadGRAB_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Actividad ya existente.
        /// </summary>
        internal static string GestActividadLOGI_DUPL {
            get {
                return ResourceManager.GetString("GestActividadLOGI_DUPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción no admite valores en blanco.
        /// </summary>
        internal static string GestActividadOBLI_DESC {
            get {
                return ResourceManager.GetString("GestActividadOBLI_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción no admite valores númericos.
        /// </summary>
        internal static string GestActividadOBLI_DESCNUM {
            get {
                return ResourceManager.GetString("GestActividadOBLI_DESCNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un estado.
        /// </summary>
        internal static string GestActividadOBLI_ESTA {
            get {
                return ResourceManager.GetString("GestActividadOBLI_ESTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Actividades.
        /// </summary>
        internal static string GestActividadTAB0_CAPT {
            get {
                return ResourceManager.GetString("GestActividadTAB0_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Actividad.
        /// </summary>
        internal static string GestActividadTAB1_CONS {
            get {
                return ResourceManager.GetString("GestActividadTAB1_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Actividad.
        /// </summary>
        internal static string GestActividadTAB1_EDIT {
            get {
                return ResourceManager.GetString("GestActividadTAB1_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Actividad.
        /// </summary>
        internal static string GestActividadTAB1_NUEV {
            get {
                return ResourceManager.GetString("GestActividadTAB1_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string GestHerramientaEspecialBTNG_CONS {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialBTNG_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string GestHerramientaEspecialBTNG_EDIT {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialBTNG_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string GestHerramientaEspecialBTNG_NUEV {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialBTNG_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión Herramientas Especiales.
        /// </summary>
        internal static string GestHerramientaEspecialFORM_CAPT {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialFORM_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición satisfactoria.
        /// </summary>
        internal static string GestHerramientaEspecialGRAB_EDIT {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialGRAB_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación Satisfactoria.
        /// </summary>
        internal static string GestHerramientaEspecialGRAB_NUEV {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialGRAB_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Herramienta Especial ya existente.
        /// </summary>
        internal static string GestHerramientaEspecialLOGI_DUPL {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialLOGI_DUPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe el número de serie.
        /// </summary>
        internal static string GestHerramientaEspecialLOGI_DUPL_SER {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialLOGI_DUPL_SER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo comentario no admite valores en blanco.
        /// </summary>
        internal static string GestHerramientaEspecialOBLI_COME {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialOBLI_COME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción no admite valores en blanco.
        /// </summary>
        internal static string GestHerramientaEspecialOBLI_DESC {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialOBLI_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción no admite valores númericos.
        /// </summary>
        internal static string GestHerramientaEspecialOBLI_DESCNUM {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialOBLI_DESCNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un estado.
        /// </summary>
        internal static string GestHerramientaEspecialOBLI_ESTA {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialOBLI_ESTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Herramientas Especiales.
        /// </summary>
        internal static string GestHerramientaEspecialTAB0_CAPT {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialTAB0_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Herramienta Especial.
        /// </summary>
        internal static string GestHerramientaEspecialTAB1_CONS {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialTAB1_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Herramienta Especial.
        /// </summary>
        internal static string GestHerramientaEspecialTAB1_EDIT {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialTAB1_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Herramienta Especial.
        /// </summary>
        internal static string GestHerramientaEspecialTAB1_NUEV {
            get {
                return ResourceManager.GetString("GestHerramientaEspecialTAB1_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string GestNeumaticoBTNG_CONS1 {
            get {
                return ResourceManager.GetString("GestNeumaticoBTNG_CONS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string GestNeumaticoBTNG_EDIT1 {
            get {
                return ResourceManager.GetString("GestNeumaticoBTNG_EDIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string GestNeumaticoBTNG_NUEV1 {
            get {
                return ResourceManager.GetString("GestNeumaticoBTNG_NUEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Gestión de Neumatico.
        /// </summary>
        internal static string GestNeumaticoFORM_CAPT1 {
            get {
                return ResourceManager.GetString("GestNeumaticoFORM_CAPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neumático dado de baja correctamente.
        /// </summary>
        internal static string GestNeumaticoGRAB_BAJ {
            get {
                return ResourceManager.GetString("GestNeumaticoGRAB_BAJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición satisfactoria.
        /// </summary>
        internal static string GestNeumaticoGRAB_EDIT1 {
            get {
                return ResourceManager.GetString("GestNeumaticoGRAB_EDIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación Satisfactoria.
        /// </summary>
        internal static string GestNeumaticoGRAB_NUEV1 {
            get {
                return ResourceManager.GetString("GestNeumaticoGRAB_NUEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Neumático ya existe.
        /// </summary>
        internal static string GestNeumaticoLOGI_DUPL1 {
            get {
                return ResourceManager.GetString("GestNeumaticoLOGI_DUPL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un tipo de banda.
        /// </summary>
        internal static string GestNeumaticoOBLI_BAN1 {
            get {
                return ResourceManager.GetString("GestNeumaticoOBLI_BAN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una Ciclo.
        /// </summary>
        internal static string GestNeumaticoOBLI_CICLO {
            get {
                return ResourceManager.GetString("GestNeumaticoOBLI_CICLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Comentario no admite valores en blanco.
        /// </summary>
        internal static string GestNeumaticoOBLI_COM1 {
            get {
                return ResourceManager.GetString("GestNeumaticoOBLI_COM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un tipo de diseño.
        /// </summary>
        internal static string GestNeumaticoOBLI_DIS1 {
            get {
                return ResourceManager.GetString("GestNeumaticoOBLI_DIS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un estado.
        /// </summary>
        internal static string GestNeumaticoOBLI_EST {
            get {
                return ResourceManager.GetString("GestNeumaticoOBLI_EST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo numero de serie no admite valores en blanco.
        /// </summary>
        internal static string GestNeumaticoOBLI_NSE {
            get {
                return ResourceManager.GetString("GestNeumaticoOBLI_NSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Tipo de neumático no acepta valores en blanco.
        /// </summary>
        internal static string GestNeumaticoOBLI_TPN {
            get {
                return ResourceManager.GetString("GestNeumaticoOBLI_TPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una Unidad de Control.
        /// </summary>
        internal static string GestNeumaticoOBLI_UC {
            get {
                return ResourceManager.GetString("GestNeumaticoOBLI_UC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Control de Neumatico.
        /// </summary>
        internal static string GestNeumaticoTAB0_CAPT1 {
            get {
                return ResourceManager.GetString("GestNeumaticoTAB0_CAPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Control de Neumático.
        /// </summary>
        internal static string GestNeumaticoTAB1_CONS1 {
            get {
                return ResourceManager.GetString("GestNeumaticoTAB1_CONS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición de Neumático.
        /// </summary>
        internal static string GestNeumaticoTAB1_EDIT1 {
            get {
                return ResourceManager.GetString("GestNeumaticoTAB1_EDIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Neumático.
        /// </summary>
        internal static string GestNeumaticoTAB1_NUEV1 {
            get {
                return ResourceManager.GetString("GestNeumaticoTAB1_NUEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo serie no admite valores 100% numéricos.
        /// </summary>
        internal static string GestNeumaticoVAL_NSERNONUM {
            get {
                return ResourceManager.GetString("GestNeumaticoVAL_NSERNONUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string GestPerfilNeumaticoBTNG_CONS {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoBTNG_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string GestPerfilNeumaticoBTNG_EDIT {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoBTNG_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string GestPerfilNeumaticoBTNG_NUEV {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoBTNG_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil de Neumático.
        /// </summary>
        internal static string GestPerfilNeumaticoFORM_CAPT {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoFORM_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición satisfactoria.
        /// </summary>
        internal static string GestPerfilNeumaticoGRAB_EDIT {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoGRAB_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación Satisfactoria.
        /// </summary>
        internal static string GestPerfilNeumaticoGRAB_NUEV {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoGRAB_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Perfil de Neumático ya existente.
        /// </summary>
        internal static string GestPerfilNeumaticoLOGI_DUPL {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoLOGI_DUPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo comentario no admite valores en blanco.
        /// </summary>
        internal static string GestPerfilNeumaticoOBLI_COME {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoOBLI_COME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción no admite valores en blanco.
        /// </summary>
        internal static string GestPerfilNeumaticoOBLI_DESC {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoOBLI_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción no admite valores númericos.
        /// </summary>
        internal static string GestPerfilNeumaticoOBLI_DESCNUM {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoOBLI_DESCNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un eje.
        /// </summary>
        internal static string GestPerfilNeumaticoOBLI_EJE {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoOBLI_EJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un estado.
        /// </summary>
        internal static string GestPerfilNeumaticoOBLI_ESTA {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoOBLI_ESTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar llantas de repuesto.
        /// </summary>
        internal static string GestPerfilNeumaticoOBLI_LLAN {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoOBLI_LLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repuesto Obligatorio.
        /// </summary>
        internal static string GestPerfilNeumaticoOBLI_REPU {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoOBLI_REPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Perfil de Neumático.
        /// </summary>
        internal static string GestPerfilNeumaticoTAB0_CAPT {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoTAB0_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Perfil de Neumático.
        /// </summary>
        internal static string GestPerfilNeumaticoTAB1_CONS {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoTAB1_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Perfil de Neumático.
        /// </summary>
        internal static string GestPerfilNeumaticoTAB1_EDIT {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoTAB1_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Perfil de Neumático.
        /// </summary>
        internal static string GestPerfilNeumaticoTAB1_NUEV {
            get {
                return ResourceManager.GetString("GestPerfilNeumaticoTAB1_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string GestPerfilUCBTNG_CONS {
            get {
                return ResourceManager.GetString("GestPerfilUCBTNG_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string GestPerfilUCBTNG_EDIT {
            get {
                return ResourceManager.GetString("GestPerfilUCBTNG_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string GestPerfilUCBTNG_NUEV {
            get {
                return ResourceManager.GetString("GestPerfilUCBTNG_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión Perfil Unidad de Control.
        /// </summary>
        internal static string GestPerfilUCFORM_CAPT {
            get {
                return ResourceManager.GetString("GestPerfilUCFORM_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición satisfactoria.
        /// </summary>
        internal static string GestPerfilUCGRAB_EDIT {
            get {
                return ResourceManager.GetString("GestPerfilUCGRAB_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación Satisfactoria.
        /// </summary>
        internal static string GestPerfilUCGRAB_NUEV {
            get {
                return ResourceManager.GetString("GestPerfilUCGRAB_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Perfil ya existe.
        /// </summary>
        internal static string GestPerfilUCLOGI_DUPL {
            get {
                return ResourceManager.GetString("GestPerfilUCLOGI_DUPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción no admite valores en blanco.
        /// </summary>
        internal static string GestPerfilUCOBLI_DESC {
            get {
                return ResourceManager.GetString("GestPerfilUCOBLI_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un estado.
        /// </summary>
        internal static string GestPerfilUCOBLI_ESTA {
            get {
                return ResourceManager.GetString("GestPerfilUCOBLI_ESTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Perfil Unidad de Control.
        /// </summary>
        internal static string GestPerfilUCTAB0_CAPT {
            get {
                return ResourceManager.GetString("GestPerfilUCTAB0_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Perfil Unidad de Control.
        /// </summary>
        internal static string GestPerfilUCTAB1_CONS {
            get {
                return ResourceManager.GetString("GestPerfilUCTAB1_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Perfil Unidad de Control.
        /// </summary>
        internal static string GestPerfilUCTAB1_EDIT {
            get {
                return ResourceManager.GetString("GestPerfilUCTAB1_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Perfil Unidad de Control.
        /// </summary>
        internal static string GestPerfilUCTAB1_NUEV {
            get {
                return ResourceManager.GetString("GestPerfilUCTAB1_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string GestTareaBTNG_CONS {
            get {
                return ResourceManager.GetString("GestTareaBTNG_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string GestTareaBTNG_EDIT {
            get {
                return ResourceManager.GetString("GestTareaBTNG_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string GestTareaBTNG_NUEV {
            get {
                return ResourceManager.GetString("GestTareaBTNG_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión Tarea.
        /// </summary>
        internal static string GestTareaFORM_CAPT {
            get {
                return ResourceManager.GetString("GestTareaFORM_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición satisfactoria.
        /// </summary>
        internal static string GestTareaGRAB_EDIT {
            get {
                return ResourceManager.GetString("GestTareaGRAB_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación Satisfactoria.
        /// </summary>
        internal static string GestTareaGRAB_NUEV {
            get {
                return ResourceManager.GetString("GestTareaGRAB_NUEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Tarea ya existente.
        /// </summary>
        internal static string GestTareaLOGI_DUPL {
            get {
                return ResourceManager.GetString("GestTareaLOGI_DUPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos una actividad.
        /// </summary>
        internal static string GestTareaOBLI_ACTI {
            get {
                return ResourceManager.GetString("GestTareaOBLI_ACTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción no admite valores en blanco.
        /// </summary>
        internal static string GestTareaOBLI_DESC {
            get {
                return ResourceManager.GetString("GestTareaOBLI_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción no admite valores númericos.
        /// </summary>
        internal static string GestTareaOBLI_DESCNUM {
            get {
                return ResourceManager.GetString("GestTareaOBLI_DESCNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un estado.
        /// </summary>
        internal static string GestTareaOBLI_ESTA {
            get {
                return ResourceManager.GetString("GestTareaOBLI_ESTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Tareas.
        /// </summary>
        internal static string GestTareaTAB0_CAPT {
            get {
                return ResourceManager.GetString("GestTareaTAB0_CAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Tarea.
        /// </summary>
        internal static string GestTareaTAB1_CONS {
            get {
                return ResourceManager.GetString("GestTareaTAB1_CONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Tarea.
        /// </summary>
        internal static string GestTareaTAB1_EDIT {
            get {
                return ResourceManager.GetString("GestTareaTAB1_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Tarea.
        /// </summary>
        internal static string GestTareaTAB1_NUEV {
            get {
                return ResourceManager.GetString("GestTareaTAB1_NUEV", resourceCulture);
            }
        }
    }
}
